### PR TITLE
Setup Backend Framework

### LINKED ISSUE #18: Create basic backend project structure
**__Task Description__**
Add a backend framework and testing framework. Set up folder structure, linter, and formatter.

**__Technical Considerations__**
Backend framework: [Django REST Framework](https://www.django-rest-framework.org/)
Testing framework: [Django REST Framework](https://www.django-rest-framework.org/)
Linter: Pylint/Flake8
Formatter: Black

**__Additional Considerations__**
Consider using OpenAPI: https://swagger.io/tools/swagger-ui/, https://editor.swagger.io/

Potentially set up CI with GitHub Actions for backend, similar to what we have for the frontend.

### PR DESCRIPTION
**Pull request by che-vee**
### Changelog
- Add Django, Django Rest Framework and Django Environs
- Add pre-commit pipeline
- Add scripts for listing and formatting
- Add .env.example file

### Requirements before review
- Python
- Pipenv - [installation guide](https://pypi.org/project/pipenv/)

### How to run
- Checkout branch locally: `git checkout feature/backend-framework`, `git pull`
- Setup virtual env: `cd server`,`pipenv shell`, `pipenv install --ignore-pipfile`
- Install git hooks in your .git/ directory: `pre-commit install`
- Setup environment variables: create `.env` file in server_api/server_api (same folder as `settings.py`), 
  generate secret key: 
  `python -c 'from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())'` and add to `.env` (`SECRET_KEY=<secret_key>`)
- Run server: `cd server_api`, `python manage.py runserver`

### CODE REVIEW

**Comment by demir-delic** [comment]
Hi @che-vee, could you please include instructions on how to run the server? And will the other features mentioned in #18 (documentation plus automated linting, formatting, and CI) be done in a separate PR?

**Comment by che-vee** [comment]
Hi @demir-delic, alright I'll included instructions. Yes, the other mentioned features in #18 will be done a separate PR.

**Review by demir-delic — APPROVED** [review]
Thanks for the instructions - I was able to run the server by following them. ✅ 

I tried to test the formatting pre-commit hook. I changed line 5 of server/server_api/destinations/apps.py to 
`default_auto_field ='django.db.models.BigAutoField'` (single quote)
then ran `git add .` and `git commit -m "temp"`. The hook didn't seem to run and the files were committed without the single quotes being corrected to double quotes. Are there some additional steps necessary to enable the pre-commit hooks?

Anyway, since you mentioned that the hooks can be added in a future PR, I'll approve this one.

**Comment by che-vee** [comment]
> Thanks for the instructions - I was able to run the server by following them. ✅
> 
> I tried to test the formatting pre-commit hook. I changed line 5 of server/server_api/destinations/apps.py to
> `default_auto_field ='django.db.models.BigAutoField'` (single quote)
> then ran `git add .` and `git commit -m "temp"`. The hook didn't seem to run and the files were committed without the single quotes being corrected to double quotes. Are there some additional steps necessary to enable the pre-commit hooks?
> 
> Anyway, since you mentioned that the hooks can be added in a future PR, I'll approve this one.

Thanks for catching that. I accidentally skipped a step in the setup instructions: **install git hooks in your .git/ directory:** `pre-commit install`. Please test out when you can, if any issues will fix in a future PR.

**Pull request merged**
